printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 card9 jrkl dok7 myo1e ap3s1 acvrl1 lgi3 tspan8 nanp nms gng2 ndrg1 efhd2 dnlz arhgap31 tifa spire2 grin1 tmprss2 qrfp dnajb7 slc17a9 itk traf3ip3 wfdc5 fabp3 she ifi44 eps8l1 cbln3 fmnl1 evx2 gpr137c tspan1 kctd4 crygb ticam2 gpr4 tmsb10 ido1 apol6 fgfr2 tmem54 hist1h1b ctsz dmrta2 htatip2 rps6kb2 il18bp gabpb2 bcl6 gsta4 sun2 efs ccdc42 tnfsf11 eomes krt18 trmt5 gpr132 scarb2 gtf2f2 dock8 ppl crip1 efcab2 krtap17-1 prpsap2 anxa6 ntrk2 samd8 slc17a7 cyb5rl flrt3 slc12a3 myh9 nudt15 cyc1 brix1 ing2 tcte1 rbl1 sgta gripap1 fuz fkbp1b myo7a tmem59 sgk3 rgma krt14 tulp2 cops4 slc6a14 acadvl snx12 wdr1 il7r ankmy1 nudt22" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_55.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 dnajb7 lgi3 spire2 gng2 ap3s1 immp2l ticam2 ndrg1 wfdc5 ntrk2 dpysl4 il18bp tspan8 nanp grin1 rbp2 she cbln3 apol6 jrkl ssh2 oxsm fgfr2 eif4ebp3 tmsb10 tnfsf11 crygb efcab2 trmt5 nms cd3g rps6kb2 ankmy1 htatip2 lag3 hrk krt18 cnga3 ido1 ubr1 scarb2 tifa hist1h1b dusp6 myo7a slc17a9 ccdc42 nr2f1 dmrta2 samd8 sla vcl traf3ip3 zfyve28 aif1l ptgir amn snap47 rasgrf1 gpr4 card9 mip rbl1 evx2 igsf1 kctd4 psmd13 vrk1 tspan1 tulp2 eomes myo1e limk2 lpar4 tmprss2 fmnl1 slc6a14 slc17a7 ifi44 hnrnpa0 pde7a pms1 bcl6 dok7 otop2 crip1 trappc6b crygc qrfp pola1 tmem86a tram1l1 heyl slco4a1 eif2b5 dlgap3 nudt15 sun2 efhd2 poldip2 nkx2-3 myo1g rfesd ankrd39 ccdc89 gabpb2 cd2bp2 zcwpw1 efna3 clic5 ftsj1 mapk8ip1 cyc1 zscan18 myh9 s100a14 fuz prkaa1 p2ry6 tcte1 rpap3 ppp1r9a mdm2 ing2 lgals1 ppp1r1a plp2 tpm1 col11a2 ttc1 ppl nmral1 osm hdac9 ubl7 nudt22 mettl10 wfikkn2 rbpj rad18 kptn gnpat rcan1 rhpn1 brix1 atp6v0e2 klf1 gata2 wdr46 prdm1 h2afv ostm1 iqgap2 klhl36 dnlz hmox2 spag7 batf3 kcnk12 pigv rgma uaca stam2 krt14 ctsz cd40 arhgef10 ahi1 mettl8 amph fndc4 cyth2 fabp3 oaz1 agpat1 pirt alg1 cd2ap hist1h1d cpne4 pmm1 slc22a17 pus10 cachd1 cd2 crb2 evpl mst1r sart1 tmx1 spred3 cdh4 kdm3a hist1h4b far1 enpp1 hook1 ino80c srp14 spopl tepp hist1h4c arhgap31 azin1 hsd17b11 psmc1 iqcb1 sdccag8 mdm1 mfhas1 prps2 lpin1 mtdh rufy4 tmem41b rbm39 lss ythdf3 krt8 rras fbxl4 myl2 ucn2 tmem54 lsm12 cops7a ube2l3 sgta recql klhl2 snrpa1 gpr132 dlx2 samm50 tbpl1 prdm10 smek2 atad5 fam129a ttc9 psmd5 inf2 mrpl16 lat2 thnsl1 slc22a4 cln3 hpca tbr1 nudcd2 atp6v0a1 eprs cox4i1 cdx2 cyb5rl terf2 gsta4 gja1 pcdhb14 fam122b casp6 cdk5 chd1l rpl10l dennd4a" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_42.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "acvrl1 ntrk2 evx2 akap3 igsf1 spire2 rps6kb2 kcnk12 amn nr2f1 myo7a slc17a9 lgi3 dok7 psd hnrnpa0 klhl36 col11a2 grin1 apol6 tnfsf11 rbl1 she samd8 tnk2 il18bp cse1l mthfd1l dnlz ing2 pirt sema4c ctnna1 otop2 ido1 card9 eif4ebp3 cars fuz immp2l gpr132 efs lag3 map3k14 pde7a crb2 son efhd2 trmt5 ppp1r9a hrk ppcs wdr11 pigv evpl mdn1 pold2 arhgef10 cyb5r1 maf n4bp3 efcab2 tbpl1 tbx10 tecpr1 limk2 rangrf rbm26 spopl abcd1 cox11 dlgap3 dhps pdcd4 mcm9 iqgap2 dsel hook2 dnajb7 dars2 stim1 etv5 hmox2 jrkl" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_4.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 dok7 grin1 il18bp she ido1 card9 ap3s1 hrk eps8l1 jrkl dnlz gng2 samd8 slc17a9 lgi3 ntrk2 apol6 evx2 gpr132 myo1e dpysl4 ftsj1 gabpb2 efcab2 immp2l lpar4 trmt5 nanp spire2 nms cyc1 hist1h1b traf3ip3 krt14 eif4ebp3 paqr3 rps6kb2 tcte1 tnfsf11 oxsm tet2 fuz ttll5 tnk2 ubxn11 gpr4 ssh2 slc25a22 ccdc42 ifi44 slc17a7 aif1l nudt15 zfyve28 pou4f2 ctsz tmem54 eomes dmrta2 dlgap3 tulp2 snx12 gsta4 ppcs rbpj arhgap31 lag3 ppp1r9a batf3 slc17a5 sun2 smek2 myl7 hook1 map3k14 rbp2 igsf1 sdccag8 evpl ubr1 fbxo44 etv5 efs tnip3 cse1l spopl mip gpnmb egr3 ccl3 fmnl1 ndrg1 klhl2 spns2 clmn ppl efhd2 anxa6 gtf2f2 amn capns1 spag7 anxa1 tmsb10 hnrnpa0 tspan2 lmf2 prkch fgfr2 rgma flrt3 ccdc103 elk3 poldip2 mtdh tbc1d10c fibp ift122 krt18 kcnn4 tspan17 dhdds fis1 brap metrnl terf2ip exph5 ing2 slc35a5 ankmy1 vcan fam122b slamf9 bcl6 esyt2 ppp1r1a mras pde7a il7r ccr5 kctd4 pofut1 lama5 ppp2r5d gnpat sbf1 atp6v1g1 trmu pigv nmral1 ipo4 far1 wdr11 mfhas1 myo7a slc25a46 tgif1 ttc9 coro1a nudcd2 bach2 ube2o chst15 lrpap1 mapk8ip1 nfatc3 mtap bahd1 tram1l1 lig3 fbxl4 gpr137c stag1 jam3 susd1 tifa lrg1 cachd1 fgfr3 taf12 osgep sec23ip sod2 p4ha2 reps2 cdh24 a2m col11a2 st3gal4 podxl ppp1cb dsel hk2 pirt scn8a mns1 sgta pip4k2b hnf1b slco4a1 fgf3 dnajb7 gja1 cpt2 pttg1ip slc39a11 gnaq srp14 kcnk12 ptgr1 usp22 cdx2 fam131c fermt3 clic5 dars2 irf1 slc15a3 pdk1 fhl2 bst2 slc36a4 dusp6 atad5 cap1 n4bp3 ppp1r14c iqcc npr1 bmper pafah1b3 slc6a18 klhl3 lrfn4 nbn zscan18 tspan8 litaf prep" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_24.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_98.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_98.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_98.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_98.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_98.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_78.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 dnajb7 htatip2 gng2 tspan8 wfdc5 wfikkn2 qrfp otop2 cbln3 ndrg1 kctd4 rufy4 ccdc42 slc6a14 nanp nms crygb sostdc1 myl2 fabp3 efhd2 hist1h1b acvrl1 ppl efcab2 noxa1 hoxc4 aif1l rbp2 sla tram1l1 srp14 ap3s1 tmsb10 mdm2 ptgir batf3 krtap17-1 tifa ticam2 lgi3 trmt5 peli3 ankmy1 hspe1 amph oxsm hdac9 hs3st3b1 immp2l slco4a1 smek2 krt18 cdx1 tmem25 apol6 pgd cnga3 rasgrf1 cd3g apcdd1 haus5 ankrd39 mbd4 slc12a3 tspan1 dmrta2 rgma gja1 gpr37l1 slc31a1 gin1 snap47 tbxas1 crygc chchd1 adsl prep tceb2 adam2 rnasel ikbke uqcr10 ift122 prlhr mettl10 fgfr2 lpar4 cyc1 s100a14 myo1g scarb2 gaa foxred1 lace1 arhgap31 ttc9 ndufv2 myo1e gtf2f1 klhl3 exoc7 rabgap1 pole3 heyl zcchc7 runx3 cdrt4 dnlz prkag1 ptpn6 rai14 fkbp1b dph2 sgta taf15 nos1ap evpl ing2 kdelc1 aif1 mst1r amn oaz1 trit1 tmem86a med8 dusp6 pmaip1 pik3cg gtf2f2 zw10 dock8 terf2ip arhgap15 ikbkg cd40 fcho2 ctsz sun2 dlx2 grin1 plekha1 rbl1 gnpat dennd4a she enpp1 tff3 cryzl1 ttc1 gata3 hira txn2 pigv eepd1 gss hist1h4d eif4ebp3 crip1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_78.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_78.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_78.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_78.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_67.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "rufy4 wfikkn2 htatip2 dnajb7 wfdc5 cbln3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_67.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_67.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_67.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_67.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_66.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 dnajb7 gng2 acvrl1 tspan8 nanp myo1e slc6a14 htatip2 ap3s1 hist1h1b nms il18bp trmt5 ndrg1 cbln3 fabp3 otop2 efhd2 dnlz crygc rufy4 wfdc5 oxsm ntrk2 rasgrf1 slco4a1 lgi3 ccdc42 krt18 sla apol6 crygb dok7 grin1 jrkl ticam2 hrk cd3g efcab2 tspan1 qrfp srp14 aif1l ing2 sostdc1 rbp2 tifa dpysl4 vcl lgals1 card9 peli3 ssh2 dock8 enpp1 anxa6 ankmy1 ppl scarb2 cnga3 tmsb10 bcl6 apcdd1 spire2 ift122 itk nkx2-3 pofut1 kptn dmrta2 prkag1 prkaa1 ostm1 pgd sun2 id2 slc22a4 vrk1 tram1l1 efs slc17a7 tmem54 ubxn11 hoxc4 coro1a krtap17-1 bach2 tulp2 ctsz inf2 ttc9 heyl prep gja1 kctd4 dlgap3 crip1 eps8l1 sgta hook1 tcte1 myo1g dlx2 rbl1 cdx2 ndufa7 bid ucn2 atad5 phf5a fermt3 azin1 she mapk8ip1 ttc1 eomes igsf1 nos1ap uqcr11 batf3 klhl3 slc25a46 gsta4 dusp6 pcyox1l noxa1 fgfr2 sod2 pde7a lig3 tmem86a hnf1b slc12a3 rpap3 tmprss2 acot2 eif2b5 efna3 hdac9 kdm3b uba52 arhgap31 samd8 fmnl1 rgma gpr4 hist1h4c fbxl4 smek2 plaur sgk3 trappc6b pbk ascc2 ubr1 bcl11b poldip2 myl6 polr1a spag7 lace1 pola1 adsl nr2f1 rpp30 acrbp rad18 cd2ap mdm2 gata2 trit1 eps15 psmd13 tceb2 klf1 prkcd ido1 nudt22 lag3 gpr132 ccdc89 gpr137c casp6 myl2 h2afv acadvl mpp6 zcwpw1 ino80c prdm1 mpped2 cpne4 eif4ebp3 recql hspe1 ppp2r5d sar1a myh9 kidins220 s100a14 ppt2 appl1 immp2l bub1 hist1h4b psmc1 wfikkn2 tnfsf11 hgs ifi44 mif4gd mtap irf1 cox4i1 paqr3 fhl2 agbl5 ppp1r1a pigv hsd17b11 ubl7 cdh24 traf3ip3 slc39a2 nudt15 cse1l gaa slc17a9 abcd1 pttg1ip prr12 gdf11 atp6v0e2 ufc1 ankrd39 slc39a4 batf ankzf1 mrpl16 ptgir tmem41b samm50 spns2 tmx1 ndufv2 pank4 bahd1 chpf2 lrg1 brd9 mis12 reep3 rpl10l rab13 elk3 prkrip1 atrip cd2bp2 myl7 zfyve27 krt14 ythdf3 cops7a upk1a hp1bp3 snx33 gin1 zfyve1 arfgap1 eno3 chst12 pole3 slc39a11 adprhl2 hist1h1d vps26a dnajc15 myo7a rfesd hpca kdelc1 galr2 mst1r mdm1 casc4" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_66.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_66.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_66.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_66.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_62.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "dnajb7 wfdc5 htatip2 crygb slc6a14 tspan1 tspan8 rufy4 qrfp cbln3 crygc noxa1 nos1ap akap3 gng2 rasgrf1 cd3g wfikkn2 ankmy1 ndrg1 ccdc42 nanp vcl srp14 efs tmsb10 hsd17b11 dock8 slc12a3 myl2 dmrta2 upk1a slc22a4 krtap17-1 efcab2 apcdd1 myo7a ticam2 haus5 lgi3 lgals1 cnga3 eomes gss uqcr11 snap47 cpne4 fabp3 slco4a1 marveld3 pms1 scarb2 igsf1 psmd14 satb2 krt18 acsbg1 nab1 foxred1 slc31a1 plaur zyx tifa aif1l atp5e clic5 lima1 enpp1 dstn osr2 ndufv2 nms fmnl1 klf1 lrrc20 dnlz rab3ip samm50 ift122 pde7a gpatch4 ikbke ntrk2 cebpa efhd2 fgfr2 hist1h4d" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_62.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_62.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_62.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_62.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_125.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "ap1m1 gak ap1s2 ap1g1 dner ap1b1 kif13a ehd2 ap1s1 ap1m2 ap1ar" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_125.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_125.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_125.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_88.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "dnajb7 gng2 qrfp acvrl1 crygb nanp ap3s1 rufy4 efs efcab2 crygc pde7a igsf1 col11a2 mxra7 ubr1 dok7 card9 tspan8 tulp2 htatip2 jrkl rasgrf1 lgals1 lgi3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_88.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_88.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_88.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_84.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "nos1ap slco4a1 dnajb7 batf3 nanp rbp2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_84.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_84.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_84.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_81.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 jrkl dok7 apol6 ntrk2 evx2 lgi3 hrk oxsm spire2 card9 nms efcab2 slc17a7 dnlz samd8 il18bp ccdc42 ap3s1 traf3ip3 dnajb7 eps8l1 grin1 ssh2 ido1 nanp gabpb2 efhd2 myl7 lag3 fuz dpysl4 igsf1 efna3 hnrnpa0 ing2 tnfsf11 eif4ebp3 bcl6 cyc1 gpr4 ftsj1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_81.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_81.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_81.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_74.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 dok7 il18bp gpr132 jrkl traf3ip3 dnlz trmt5 she acvrl1 ido1 card9 eps8l1 spire2 grin1 apol6 tmem54 myo1e evx2 heyl anxa1 gng2 nms ifi44 samd8 ppp1r14c ppl" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_74.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_74.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_74.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_73.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "dok7 akap3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_73.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_73.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_73.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_7.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_7.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_7.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_7.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_6.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_6.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_6.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_6.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/C57twocell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_56.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 evx2 il18bp dok7 otop2 ccdc42 card9 spire2 ndrg1 grin1 dnlz trmt5 jrkl ppl lgi3 samd8 apol6 efhd2 ido1 tmem54 aif1l ntrk2 hoxc4 dnajb7 efcab2 gng2 hrk gabpb2 tram1l1 kctd4 rgma ctsz tifa eif4ebp3 slc17a7 nanp oxsm nms ftsj1 ap3s1 gpr132 ubxn11 cnga3 heyl pde7a myl7 tnfsf11 prdm10 sun2 zbtb33 zfyve28 tet2 eps8l1 myo1e arhgap31 kdm3b qrfp rps6kb2 tmsb10 nmral1 sostdc1 spag7 dock8 traf3ip3 zcwpw1 she srp14 scarb2 col11a2 fhl2 eif2b5 arl6ip4 amn ttll5 slc6a18 atad5 ccnc cxcl2 kptn myl2 snx12 prkch zbtb48 trappc6b plaur esyt2 tmem86a slc6a14" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_56.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_56.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_56.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_52.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "ap3s1 akap3 apol6 lgi3 dnlz" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_52.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_52.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_52.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_47.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 rufy4 wfikkn2 evx2 myl2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_47.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_47.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_47.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_46.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_46.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_46.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_46.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_44.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 akap3 tspan8 prlhr gng2 slc6a14 slc12a3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_44.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_44.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_44.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_43.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 evx2 samd8 trmt5 efcab2 slco4a1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_43.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_43.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_43.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_37.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 lgi3 nanp cbln3 gng2 dnajb7 ap3s1 slc6a14 grin1 apol6 acvrl1 ndrg1 efcab2 myo1e tmsb10 ccdc42 qrfp she wfdc5 dmrta2 aif1l tspan8 sla hist1h1b htatip2 il18bp scarb2 kctd4 eif4ebp3 tspan1 cyc1 evx2 crygc eomes trmt5 cd3g ido1 spire2 lag3 rbp2 arhgap31 ptgir batf3 immp2l tnfsf11 card9 slco4a1 srp14 ift122 ticam2 gpr4 nms vcl dok7 vrk1 ubr1 dnlz oxsm tmem54 ppl rgma mbd4 acsbg1 crip1 bcl6 dock8 hook1 fabp3 dlgap3 efhd2 hist1h4b efs dpysl4 p2ry6 igsf1 slc22a4 prep myl7 traf3ip3 slc17a9 myh9 rps6kb2 pde7a krtap17-1 hsd17b11 tmprss2 krt18 ntrk2 eps8l1 amph tjp2 rbm39 rufy4 nudt15 cnga3 limk2 rpap3 fgfr2 ppcs ankmy1 rbl1 zfat ssh2 plaur rhpn1 klhl3 hrk fam131c hdac9 ostm1 clic5 txn2 klhl36 tbcd paqr3 nmral1 arhgef10 slc12a3 myo7a ubxn11 hist1h4d eps15 ing2 smek2 hnf1b psd slc17a7 samm50 ndufv2 ctsz slc17a5 crygb ttc1 pofut1 myo1g sgta rasgrf1 wfikkn2 pik3cg mrpl16 hs3st3b1 tifa hspe1 lsm12 poldip2 fmnl1 adam2 jrkl zbtb33 gsta4 sun2 gin1 gja1 brix1 gaa prss35 mip sgk3 hist1h1d bach2 ttll5 n4bp3 recql prpsap2 gnaq snap47 atrip c1ql4 myl12b efna3 setmar haus5 poc1b slc31a1 ogdh rad18 atp6v1g1 hist1h4c appl1 klf1 fam122b ftsj1 ngdn man2b1 jtb prkaa1 ccdc134 mettl4 tubg1 pola1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_37.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_37.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_37.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_36.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 rufy4 htatip2 nanp akap3 tspan8 dnajb7 sla crygc slco4a1 kctd4 ccdc42 nms cbln3 cd3g gng2 aif1l rasgrf1 lgi3 fabp3 efhd2 srp14 tspan1 arhgap15 dmrta2 myo1g fgfr2 qrfp hcls1 crygb slc6a14 hs3st3b1 psmd13 eomes apcdd1 dock8 hist1h1b ptgir batf apol6" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_36.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_36.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_36.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_35.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "jrkl akap3 she acvrl1 hrk dok7 traf3ip3 spire2 ap3s1 card9 oxsm ifi44 evx2 ido1 myo1e gpr137c gabpb2 il18bp dpysl4 gpr132 nms samd8 eps8l1 tnfsf11 ftsj1 dlgap3 trmt5 flrt3 snx12 lgi3 arhgap31 grin1 dnlz hoxc4 kcnn4 prdm10 slc17a7 kif13a sostdc1 tslp immp2l ppp1r14c slc17a9 ubxn11 slc25a22 tet2 egr3 tcte1 rgma zfyve28 ntrk2 ndrg1 fam131c nmral1 aif1l paqr3 rps6kb2 peli3 krt14 spag7 mamdc4 ttc9 il7r otop2 myl7 hook1 ing2 aldoa gripap1 cxcl2 pak6 slc15a3 rnh1 skap2 dusp6 sun2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_35.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_35.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_35.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_31.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 evx2 tspan1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_31.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_31.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_31.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_27.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "acvrl1 dok7 akap3 ido1 il18bp jrkl card9 hrk gpr132 apol6 slc17a9 traf3ip3 myo1e dnlz flrt3 samd8 dpysl4 ap3s1 gabpb2 lag3 nanp tifa gpr137c eif4ebp3 evx2 mip grin1 hoxc4 she anxa1 ifi44 paqr3 slamf9 nms ccl3 tram1l1 tslp" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_27.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_27.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_27.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_23.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 htatip2 rufy4 slc12a3 tspan1 wfikkn2 mxra7 noxa1 evx2 tspan8 crygc gng2 crygb athl1 gp2 btd rorc klc1 tmem25 rasgrf1 pcsk6 icam2 dnajc16 h6pd slc6a14 rrm2 cbln3 hrct1 dnajb8 ptcd3 cog5 sfxn5 hsd17b11 mrps35 prlhr psmd4 psmc1 qrfp kdelc2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_23.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_23.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_23.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_22.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 lgi3 ap3s1 samd8 she grin1 trmt5 hist1h1b ttll5 hs3st3b1 hnrnpa0 acvrl1 evx2 eif4ebp3 rbp2 apol6 capns1 itk" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_22.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_22.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_22.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/ES
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_21.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 heyl jrkl sostdc1 acvrl1 tspan2 klc1 traf3ip3 hoxc4 otop2 samd8 dchs1 card9 il18bp galr2 hist1h1b ifi44 hpca fst lsr dkk1 birc7 cobll1 cplx2 nr4a3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_21.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_21.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_21.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_15.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "evx2 akap3 wfdc5 rufy4 myl2 wfikkn2 jrkl ctnna1 trpc6 trmt5 noxa1 acvrl1 ido1 pcsk6 gp2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_15.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_15.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_15.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_13.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 dok7 acvrl1 ido1 il18bp jrkl traf3ip3 otop2 dpysl4 hoxc4 card9 oxsm sostdc1 egr3 gabpb2 hpca slc17a9 arhgap31 samd8 evx2 gpr132 grin1 eps8l1 syt13 peli3 bcl6 heyl trmt5 hrk ifi44 she spire2 apol6 immp2l tcte1 tspan2 anxa1 nms metrnl myo1e tslp ppp2r5d rps6kb2 ptprg nanp lpar4 sec24d wnt11 spag7 lag3 prdm10 gpr4 ppl ap1s2 pros1 fam131c nmral1 taf7l lgi3 tram1l1 gpr137c stag1 mip paqr3 fam101a ftsj1 zscan18 ubxn11 kcnn4 smek2 ntrk2 ttc9 atg2b cyc1 rala dse serpinh1 ccr5 sp8 hist1h1b cxcl2 gripap1 tnfsf11 dkk1 zfp37 slc17a7 tmem54 zcwpw1 pdia4 fbxo44 trpc6 tet2 leprotl1 zfp91 tyro3 fam129a agpat3 mbtps1 ppp1r14c pth1r n4bp3 cdk9 tbc1d5 dhx35 tgfb1i1 myl2 rbbp5 gdf11 efhd2 neurl4 flrt3 pstk mettl4 ccnc esyt2 ccl3 gns dyrk1a dlx6 ankrd54 nars2 cd164 birc7 abhd5 itpkb slamf9 npr1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_13.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_13.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/PrE
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_13.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_10.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfikkn2 rufy4 cbln3 noxa1 dpysl2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_10.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_10.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_10.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/C57twocell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_1.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 grin1 acvrl1 she dok7 il18bp oxsm myo1e spire2 ssh2 ido1 lpar4 evx2 tram1l1 apol6 tnfsf11 tcte1 amn trmt5 klhl36 smek2 nr2f1 kctd4 slc17a9 ntrk2 hrk tulp2 cxcl2 traf3ip3 slc35a5 lag3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_1.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_1.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_1.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_60.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "trio cdc5l prpf3 prpf19 plrg1 cetn2 sfi1 naa40 ctnnbl1 setmar cwc15 bcas2 emid1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_60.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_60.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_59.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cd46 cd9 cd82 itga7 cd151 itga3 mmp7 ptgfrn clgn adam2 hbegf" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_59.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_59.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_57.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "eif3h eif3a eif3i eif3f eif3l eif3b eif3d eif3c eif3e fbxo32 eif4a2 eif3g eif3k usp3 prrc2b eif1b eif3m tmem203" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_57.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_57.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_41.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "ndufs1 atp5f1 ndufa12 ndufb9 ndufs4 ndufb10 ndufs7 ndufb5 cyc1 msln cox15" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_41.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_41.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_325.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "ripk1 tnfaip3 casp8 tradd tnfrsf1a dedd cflar traf1 fadd nucb2 casp8ap2 casp6 tnfrsf10b pcyt1a fas tnfrsf25 clip3 tnfrsf21 plin4" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_325.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_325.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_301.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "tada2b yeats2 tada2a dr1 kat2a mbip csrp2bp wdr5 zzz3 usp22 dock6 luzp1 drap1 tada3 helt" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_301.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_301.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_280.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "gsn pxn tln1 tgfb1i1 ptk2 vcl bcar1 nedd9 pkd1 nphp1 sele ptk2b git1 ptprh tns1 sorbs1 nrap sh2d3c coro2b" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_280.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_280.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_238.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "ash2l kdm6a chd8 setd1a rbbp5 wdr82 kifc1 wdr5 pygo2 cxxc1 pax7 kdm4b hcfc2 kdm6b ulk3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_238.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_238.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_227.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "srgap3 wasf1 gas7 dnmbp nckap1 wasf2 abi1 cyfip1 cyfip2 wipf3 vstm2l" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_227.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_227.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_223.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "pdgfra bcar1 nedd9 crkl dock3 crk krt76 shb krt12 rapgef1 cass4 sh3bp1 map4k5 avil" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_223.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_223.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_222.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cpsf3l ints2 ints3 ints5 ints12 ints7 ints9 ints10 ddx26b ints8 ints4 naif1 ints6" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_222.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_222.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_204.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "mir196b pbx2 pknox1 pbx1 meis2 meis1 hoxd9 hoxa9 hoxb1 hoxd11 tlx1 pknox2 hoxb8" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_204.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_204.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_201.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cbx4 cbx2 rnf2 cbx8 scmh1 ccdc158 pcgf2 bmi1 pcgf6 phc1 phc3 phc2 ring1 cbx7 pcgf5 pcgf1 fbrs yaf2 zfp42 pcgf3 rybp trank1 ankrd26" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_201.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_201.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_197.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cyb5b mrps16 mrpl32 nfkbil1 mrps22 mrps26 mrps9 mrpl42 mrps35 mrps28 mrps18b mrps25 mrpl21" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_197.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_197.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_193.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cpsf3l shfm1 ints2 ints3 ints5 ints12 ints7 ints9 ints10 ints8 ints4 naif1 ints6 sac3d1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_193.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_193.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/C57twocell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_186.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "vamp8 snap25 stxbp1 syt4 stx3 stx2 doc2b doc2a unc13b stx1b cplx2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_186.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_186.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/C57twocell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_133.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "taf3 taf7 taf1 taf11 taf15 taf9 taf6 taf10 taf5 eny2 taf7l taf9b taf5l taf12 taf13 usp22 atxn7l3 supt7l taf2 taf4b taf6l pofut2 ercc1 atxn7l3b taf8" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_133.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_133.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/early2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_12.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "arhgap9 mapk3 mapk1 dusp1 rps6ka4 ier3 ptpn7 ptprr mapk14 ptpn5 gmfb dusp6 dusp4 dusp2 dusp5" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_12.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_12.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/4cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_107.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "btg2 cnot3 btg3 cnot8 cnot7 cnot2 cnot1 rqcd1 cnot10 cnot6l tnrc6c cnot6 popdc2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_107.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_107.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/C57twocell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_10.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "cd82 muc1 egfr ptk6 erbb3 erbb2 lrig1 btc anks1b erbb4 tgfa adam17 ctgf cmtm8 ereg hbegf" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_10.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/ppi_10.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/zy
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_99.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_99.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_99.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_96.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "hoxc4 otop2 peli3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_96.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_96.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_94.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_94.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_94.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_93.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_93.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_93.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/late2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_92.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "lgi3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_92.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_92.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_91.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "jrkl gpr132 wfdc5 card9 wfikkn2 acvrl1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_91.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_91.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_90.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfikkn2 myl2 htatip2 rufy4 cnga3 qrfp crygb cbln3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_90.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_90.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_9.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_9.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_9.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_89.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 acvrl1 lgi3 spire2 nanp slc17a7 nms ntrk2 she dnajb7 grin1 tnfsf11 apol6 gng2 samd8 ssh2 cnga3 efcab2 aif1l ido1 dpysl4 myo7a hrk slco4a1 il18bp myo1e evx2 myl2 ankmy1 pirt hook1 rps6kb2 oxsm sla qrfp ing2 nr2f1 ubr1 lag3 ndrg1 jrkl eif4ebp3 traf3ip3 col11a2 rbl1 tulp2 myl7 gpr4 pde7a clic5 immp2l trmt5 crygb cse1l card9 eps8l1 ubxn11 dock8 efhd2 bub1 eif2b5 scarb2 tnk2 kidins220 pou4f2 spag7 slc25a46 recql plaur ap3s1 efs ppcs slc35a5 rasgrf1 crb2 smek2 arhgap31 arl6ip4 poc1b srp14 limk2 fam131c fmnl1 klhl36 ifi44 batf3 hist1h1b chpf2 dhdds dusp6 ppp1r9a mip nln cyc1 nudcd2 gabpb2 vcl rgma hist1h4b rbp2 capns1 ccdc42 krt18 acvr2b casc4 ticam2 slc35a4 fhl2 taf12 rab3ip dph2 poldip2 hdac9 hoxc4 gaa hoxc9 dsel cbln3 uros evpl fam129a tifa slc17a9 pold1 atad5 lace1 amn mns1" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_89.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_89.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_87.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "otop2 sostdc1 wfikkn2 rufy4 wfdc5 myl2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_87.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_87.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_86.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "rufy4 wfikkn2 wfdc5 slc12a3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_86.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_86.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_85.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "dnajb7 qrfp" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_85.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_85.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_83.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 htatip2 myl2 slc12a3 nanp rufy4 rasgrf1 noxa1 dnajb7 crygb tspan1 cd3g pcsk6 sostdc1 qrfp mxra7 tmem25 h6pd" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_83.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_83.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_82.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "qrfp gng2 rasgrf1 akap3 tspan8 htatip2 ankmy1 lgi3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_82.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_82.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_80.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "evx2 acvrl1 she lgi3 akap3 traf3ip3 dpysl4 arhgap31 jrkl sostdc1 card9" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_80.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_80.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/8cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_79.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 ido1 card9 ankmy1 heyl hoxc4 traf3ip3 gng2 il18bp dnajb7 nanp jrkl peli3 otop2 efcab2 hist1h1b ndrg1 sostdc1 hpca dok7 efhd2 oxsm ppl cnga3 acvrl1 dpysl4 tmem54 ap3s1 samd8 cdx2 dmrta2 sdccag8 spire2 arhgap31 prep aif1l myo1e kctd4 nms tjp2 gpr132 tram1l1 tcte1 ubxn11 snap47 gpr137c ntrk2 trmt5 slc6a18" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_79.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_79.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_76.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "otop2 sostdc1 akap3 heyl gng2 nanp itk ndrg1 dnajb7 hoxc4 ppl hist1h1b apol6 cbln3 tspan8 trmt5 ccdc42 ap3s1 peli3 sla htatip2 dmrta2 hpca wfdc5 mdm2 krt18 lgals1 tram1l1 hrk nms crygc trit1 tmem54 ticam2 gsta4 hspe1 lgi3 slc22a4 ctsz spire2 acvrl1 mamdc4 slc6a14 kptn crip1 eif3h kctd4 grin1 dpysl4 s100a14 pou3f3 ttll5 slco4a1 prkag1 mapk8ip1 rufy4 azin1 inf2 arl6ip4 jrkl eif4ebp3 gata2 tspan1 sod2 dlx2 crygb" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_76.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_76.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_72.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "acvrl1 jrkl il18bp akap3 evx2 evpl nms card9 dok7" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_72.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_72.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/midblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_68.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 gp2 athl1 btd celf2 maf f8" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_68.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_68.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_64.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "rufy4 otop2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_64.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_64.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_61.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "jrkl" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_61.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_61.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_59.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "grin1 acvrl1 card9 otop2 sostdc1 il18bp hrk jrkl dok7 ido1 tram1l1 slc17a7 ntrk2 spire2 samd8 ftsj1 gng2 gpr132 ankmy1 hoxc4 heyl oxsm gpr137c arhgap31 nmral1 tnfsf11 gabpb2 peli3 metrnl myo1e tifa nanp ccdc103" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_59.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_59.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_54.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "sostdc1 otop2 wfdc5 dnajb7 akap3 gng2 wfikkn2 crygb slc6a14 acvrl1 cbln3 hist1h1b fabp3 qrfp heyl crygc hpca hrk tspan8 htatip2 noxa1 efhd2 nanp hoxc4 arl6ip4 gdf11 scarb2 fam101a tifa" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_54.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_54.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_50.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "otop2 dnajb7 acvrl1 grin1 hoxc4 nanp myl2 heyl ntrk2 gng2 hrk oxsm hpca srp14 sostdc1 rufy4 akap3 lgi3 hist1h1b cnga3 tnfsf11 she ankmy1 smek2 aif1l samd8 fbxl4 slco4a1 trmt5 cbln3 zfyve28 nms dpysl4 dock8 ticam2 efcab2 mip" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_50.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_50.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/earlyblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_5.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "otop2 hoxc4" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_5.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_5.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/fibroblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_49.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_49.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_49.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/16cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_34.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3 apol6 nanp traf3ip3 jrkl gng2 tspan8 dnlz nms ido1 eps8l1 dnajb7 gabpb2 lgi3 aif1l rgma htatip2 ttc9" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_34.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_34.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_26.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "otop2 sostdc1 dnajb7 rufy4 peli3 hoxc4 wfikkn2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_26.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_26.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/mid2cell
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_20.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 dok7 card9 akap3 tifa slc6a14 crygb nanp ccdc42 fabp3 traf3ip3 apol6 nms tspan8 ankmy1 gpr132 qrfp jrkl aif1l ido1 cd3g trmt5 gng2 myo1e hist1h1b" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_20.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_20.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/lateblast
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_16.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "wfdc5 htatip2 myl2 wfikkn2 rasgrf1 rufy4" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_16.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_16.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BMDC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_14.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "sostdc1 evx2" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_14.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_14.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
printf "query\tsignificant\tp_value\tT\tQ\tQ&T\tprecision\trecall\tterm_id\tdomain\tgroup\tdescription\tdepth\tintersection\tevcodes\n" > GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_12.txt
python ~/gprofiler-official-0.2.3/gprofiler.py -o mmusculus "akap3" >> GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_12.txt
cp GO_analysis_gprofiler_results/deep_ana0.08.csv/all_groups/dense_12.txt GO_analysis_gprofiler_results/deep_ana0.08.csv/BXC
